version: '3.8'
services:
  postgresql:
    container_name: yts_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'yts'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'yts'
    ports:
      - '5432:5432'
volumes:
  postgresql:
    driver: local
